[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://genuine-meringue-e2a564.netlify.app/*"
  to = "https://genuine-meringue-e2a564.netlify.app/:splat"
  status = 301
  force = true
